---
- name: Install jenkins by using ansible
  hosts: dev
  become: yes
  tasks:
    - name: Install Java using Ansible
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    
